### ISSUE TITLE
The (Basic) Mistakes I wish I could have avoided

### ISSUE THREAD

**Issue by sathishk** [elastic/call-for-meetups#11]
Title: The (Basic) Mistakes I wish I could have avoided
Speaker: Sathish Kumar Thiyagarajan
City: Singapore
Country: Singapore
Language: English
Type: [Presentation 30-45 mins]
Level: [Standard]
Tags: [devops]
Description
I would like to talk about the basic mistakes that I should have avoided in my previous implementations using elastic search. I will walk through the case studies that will show how different projects need a different approach to Elastisearch usage.

Speaker Bio
I am Sathish Kumar Thiyagarajan working as a Solution Architect. I practice Open Source technologies (both by using as well as contributing) around Java, NoSQL Databases and Web. I believe speaking about/listening to technology is the best way to learn and you can find me doing the same in meetups around Singapore, Chennai, and Bengaluru.

**Comment by xeraa** [comment]
@cforchangning I think you're the best one to coordinate this one, right :)?

**Comment by aravindputrevu** [comment]
@sathishk You know we have an Elastic{ON} Singapore in Feb. We're looking to plan a meetup. Will keep you updated. Thanks for reaching out here.

**Comment by sathishk** [comment]
Thanks @aravindputrevu

**Comment by cforchangning** [comment]
Thanks @xeraa  @aravindputrevu! 

@sathishk thanks for reaching out! :) we have a [meetup planned on Feb 19th](https://community.elastic.co/events/details/elastic-elastic-singapore-user-group-presents-elastic-february-meetup-at-microsoft/#/) before ElasticON Singapore and we're looking for one more speaker. Will you be free then?

**Comment by sathishk** [comment]
Sure @cforchangning . I can talk on 19th Feb

**Comment by cforchangning** [comment]
Great @sathishk, do you mind dropping me an email to coordinate this further? ning.chang@elastic.co Cheers!
