### ISSUE TITLE
Personalized music content search implementation

### ISSUE THREAD

**Issue by gunayus** [elastic/call-for-meetups#13]
* **Title**: Personalized music content search implementation
* **Speaker**: Erdem Günay
* **City**: İstanbul
* **Country**: Turkey
* **Language**: English
* **Type**: Hands-on coding, minimal implementation of an actual solution 30-45 mins 
* **Level**: Standard
* **Tags**: live-coding, workshop, personalization

**Description**
In this virtual meetup, we will go over step-by-step how we have replaced our music platform's search capabilities with Elasticsearch achieving better and personalized results based on user's previous music taste.
 
*A paragraph describing your proposal*
we will go over 
 - different types of analyzers and use cases for each analyzer
 - Java Rest high level client
 - Usage of simple query builders for matching content
 - Usage of function score query builder for personalized search results boosting

**Speaker Bio**
I work at Turkcell, the biggest mobile telecom operator in Turkey, since 2005 as a principal solution architect, responsible for enterprise application platforms serving all our digital apps’ clients (mobile apps, web apps, STBs, Android, Apple tvs, smart tvs, etc.). Beside my professional responsibilities, I am founder of Istanbul Spring Meetup group where I organize meetups on Spring framework and Spring features regularly.

*Short bio of the speaker*

**Comment by daliyasp** [comment]
Hi Erdem! I hope you are well and safe! Could you please give me your email address so I can put you in touch with our organizer from Turkey? We can also discuss further details there. Thank you!

**Comment by gunayus** [comment]
sure @daliyasp 
e.gunay@gmail.com
