### ISSUE TITLE
Using Elasticsearch as a Time-Series Database in the Endpoint Agent

### ISSUE THREAD

**Issue by ssouris-te** [elastic/call-for-meetups#14]
* **Title**: Using Elasticsearch as a Time-Series Database in the Endpoint Agent
* **Speaker**: Stathis Souris
* **City**: Virtual, London
* **Country**: Virtual, UK
* **Language**: English
* **Type**: Presentation 30-45 mins
* **Level**: Standard
* **Tags**: [monitoring, time-series]

**Description**

At [ThousandEyes](https://www.thousandeyes.com/) and the [Endpoint Agent](https://www.thousandeyes.com/product/end-user-monitoring), we have a track record of using Elasticsearch as a time-series database for the metrics that we collect from our agents. 
I will be presenting how we decided to use Elasticsearch as a Time Series Database (TSDB), and how we got buy-in from stakeholders. 

**Speaker Bio**

Stathis spent several years in Athens, Greece, as a Software Engineer before moving to London. Enjoys working with large distributed systems using technologies like Elasticsearch, Kafka, Java, Kotlin. Wants to build his own tech when he grows up.

**Comment by ssouris-te** [comment]
This talk was done :)
Here is the youtube link: https://www.youtube.com/watch?v=imbMqNb5LwU

Thank you all for giving me the opportunity :)

**Comment by xeraa** [comment]
Thanks for doing the talk :)
