### ISSUE TITLE
[Idea] Technical Writing and Elastic Documentation

### ISSUE THREAD

**Issue by a03nikki** [elastic/call-for-meetups#15]
* **Title**:
* **Speaker**:
* **City**: Minneapolis
* **Country**: United States
* **Language**: English
* **Type**: Presentation 30-45 mins
* **Level**: [Introduction | Standard | Advanced]
* **Tags**: [monitoring, devops, live-coding, workshop,...]

**Description**

*A paragraph describing your proposal*

**Speaker Bio**

*Short bio of the speaker*

**Potential Outline**

1. Introduction
    - Where? https://www.elastic.co/guide/index.html
    - Who? (target audience)
    - What? (documentation by a set of html pages)
    - When? (versioned)
    - Why? (do the things)
    - How? (search box, outlines, formatting)
2. Technical Writing
    - Skill we all use
    - What makes good writing?
3. Maintaining Elastic doc (maybe)
    - stored in Github
    - tech that is used to generate it
4. Contributing to doc
    - takes lots of times to maintain
    - lots of content to maintain with all the version updates

**Comment by Dinomoe** [comment]
Hey @a03nikki! This also looks awesome.

When were you thinking of presenting?
Do you need any help/assistance? I always like to offer "speaker assistance" to make your life easier.

-George

**Comment by a03nikki** [comment]
@Dinomoe : Thank-you for your offer of help.  This is more of an idea at this point then anything definitive at this point. I'll make sure it gets passed along to however may take the topic.

CC: @josephPresseller
