### ISSUE TITLE
[Idea] Elastic release updates

### ISSUE THREAD

**Issue by a03nikki** [elastic/call-for-meetups#16]
* **Title**:
* **Speaker**:
* **City**: Minneapolis
* **Country**: United States
* **Language**: English
* **Type**: Presentation 30-45 mins
* **Level**: [Introduction | Standard | Advanced]
* **Tags**: [monitoring, devops, live-coding, workshop,...]

**Description**

Michael Heldebrant did a session called [Updates in Elastic 6.x](https://www.meetup.com/Minneapolis-Elastic-Fantastics/events/252234363/) in August 2018.  It would be helpful to do one or more sessions for the 7.x series.

**Speaker Bio**

*Short bio of the speaker*

**Comment by Dinomoe** [comment]
Hey @a03nikki! This is a great idea! I have a few follow up questions:

- When were you thinking of presenting?
- Do you need any help/assistance? I always like to offer "speaker assistance" to make your life easier.

To get started I think we will need:
Title:
Abstract:
Speaker Bio:

Please let me know if you have any questions.

-George

**Comment by a03nikki** [comment]
@Dinomoe : Thank-you for your offer of help.  This is more of an idea at this point then anything definitive at this point. I'll make sure it gets passed along to however may take the topic.  I left them blank as I don't know who would present or if this will happen.

CC: @josephPresseller
