### ISSUE TITLE
Title : Smart analysis using Elastic

### ISSUE THREAD

**Issue by VivekPemawat** [elastic/call-for-meetups#19]
* **Title**: Smart Analysis using Elasticsearch
* **Speaker**: Vivek Pemawat
* **City**: Virtual
* **Country**: Virtual
* **Language**: English
* **Type**: [Presentation 20 mins]
* **Level**: [Standard]
* **Tags**: [logs-analysis,search,devops]

**Description**

*In this talk Vivek Pemawat is going to present how at Cloudera we used Elasticsearch to build a Log analysis tool to automate  process of manual debugging of System test and E2E runs running at scale and make life of Engineers easy.
Automatically jira is suggested and RCA (root cause analysis) of failures is done by tool with TBs of logs ingested daily basis.*

**Speaker Bio**

*I work at Cloudera,  Infrastructure and Tools teams as Staff Software Engineer leading multiple projects related to Infrastructure and tooling like Logging and Monitoring infra , Log analysis tool and Workflow Platform.
I have experience on Infrastructure and tooling for more then 10 years.*

**Assign to the Community team**

Africa, Europe, Middle East: @daliyasp and @ossanna16
Asia, Austrailia, and Pacific: @y-michael
North America and South America: @fw-at-elastic, @phoebequincy, and @ullyta

**Comment by ossanna16** [comment]
@Y-Michael @aravindputrevu Vivek is based in India. Do you mind reaching out to him regarding presenting at a meetup?

**Comment by aravindputrevu** [comment]
@ossanna16 sure Anna, Vivek reached out to me already!

**Comment by VivekPemawat** [comment]
@ossanna16  @aravindputrevu thank you so much!!
