### ISSUE TITLE
Hacking the culture at Mango IT

### ISSUE THREAD

**Issue by albertogutimac** [elastic/call-for-meetups#2]
* **Title**: Hacking the culture at Mango IT 
* **Speaker**: Alberto Gutiérrez Maceiras, Juan Antonio Soto Tamayo y Xavi Ribera Sabaté
* **City**: Barcelona
* **Country**: Spain
* **Language**: Castellano
* **Type**: Presentation 30-45 mins 
* **Level**: Standard 
* **Tags**: monitoring, devops, analytics

**Description**

En esta presentación hablaremos  de la transformación digital en Mango IT. Este es un proceso que comenzó hace un par de años donde se apostó tanto por una fuerte subida en el stack tecnológico como en un enfoque más Agile. 

Basaremos la presentación explicando como la pila ELKB nos ha ayudado en el proceso de transformación. Principalmente analítica orientada a cliente y sistema de logs en contenedores cloud.

Finalmente tocaremos la visión de futuro que se encuentra muy ligada a temas de machine learning basándonos en elastic.  

**Speaker Bio**
**Alberto Gutiérrez Maceiras**
Alberto es un Agile Coach que hace especial foco en la calidad de los diseños, arquitectura y código. Está especializado en Leading Change y hacking the culture para crear nuevos entornos donde la innovación y excelencia puedan florecer.

**Xavi Ribera Sabaté**
Xavi Ribera trabaja como backend lead en Mango IT. Especialista arquitectura y desarrollo de aplicaciones basadas en microservicios e implementadas en tecnología Spring Boot + Java 8 o Kotlin. Apasionado en el desarrollo de aplicaciones móviles, intenta convivir entre el mundo del backend y del mobile sin acabar loco.

**Juan Antonio Soto Tamayo**
Juan Antonio es Arquitecto backend en Mango. Ha trabajado de manera activa en la antigua arquitectura java basada en Spring. Experto en base de datos (SQL, NoSQL). En este momento está dentro del equipo que está llevando a cabo la migración a microservicios.
Me encanta descubrir nuevas tecnologías y IOT.

**Comment by immavalls** [comment]
Event planned https://www.meetup.com/es-ES/Barcelona-Elastic-Fantastics/events/258640426/
