### ISSUE TITLE
Using Elasticsearch Percolation to match new real estate listings against saved searches

### ISSUE THREAD

**Issue by davidbkemp** [elastic/call-for-meetups#20]
* **Title**: Using Elasticsearch Percolation to match new real estate listings against saved searches
* **Speaker**: David Kemp
* **City**: Melbourne
* **Country**: Australia
* **Language**: English
* **Type**: Presentation 30-45 mins
* **Level**:  Standard
* **Tags**: percolation

**Description**

Elasticsearch's percolation feature allows REA Group to send daily notifications to users of realestate.com.au to alert them when new real estate listings match their saved searches.
In this talk, David will describe Elasticsearch percolation and how REA Group uses it to match thousands of new listings per day against millions of saved searches.

**Speaker Bio**

David Kemp is a Principal Developer with a Search specialisation at REA Group.
David has worked with search technologies for more than 12 years, and with Elasticsearch specifically for more than 8 years.

**Assign to the Community team**

Africa, Europe, Middle East: @daliyasp and @ossanna16
Asia, Austrailia, and Pacific: @y-michael
North America and South America: @fw-at-elastic, @phoebequincy, and @ullyta

**Comment by markwalkom** [comment]
@davidbkemp can you drop me an email so we can chat about this?

**Comment by davidbkemp** [comment]
> @davidbkemp can you drop me an email so we can chat about this?

Hey Mark, I don’t seem to have your email address, so I have sent you a connection request on Linkedin.

By the way, I assume you know that I did give the talk for  the Elastic User Group last year?

https://www.youtube.com/watch?v=3i-KMOqhyZ4

**Comment by markwalkom** [comment]
Ahh yeah sorry, I misread the date there :)
