### ISSUE TITLE
Elastic Query-DSL & Aggregations

### ISSUE THREAD

**Issue by vinnu1812** [elastic/call-for-meetups#22]
* **Title**: Elastic Query-DSL & Aggregations
* **Speaker**: Vinod Kumar
* **City**: Bangalore
* **Country**: India
* **Language**: English
* **Type**: Presentation 30-45 mins
* **Level**: [Introduction | Standard ]
* **Tags**: Demo, live-coding, workshop

**Description**

*Elastic Overview about it's query capabilities and great support for Domain specific language and aggregations with examples. Will cover real world examples and working session hands on demo for the above concepts*

**Speaker Bio**

*Vinod is working as senior software engineer at Lowe's India, has 6+ years of working experience with retail domain and e-commerce search. Loves to solve information retrieval problems and enjoys working around improving relevancy of the systems*

**Comment by fw-at-elastic** [comment]
Hi Kawnish and Ashish- I want to flag this for you as I'm unsure if you're
subscribed to these notifications- I haven't seen one of these in a while.

**Comment by ashishtiwari1993** [comment]
Yeah we have started accepting CFP here for the Meetup.
