### ISSUE TITLE
Elastic Introduction & Threat Intel

### ISSUE THREAD

**Issue by Shrikantgulia** [elastic/call-for-meetups#25]
* **Title**: Elastic Introductions & Threat Intel
* **Speaker**: Shrikant
* **City**: Delhi/NCR
* **Country**: India
* **Language**: English
* **Type**: [Presentation 30-45 mins | Lightning talk 5-10 mins]
* **Level**: [Introduction | Standard | Advanced]
* **Tags**: [monitoring, ThreatIntel, Wazuh, workshop,...]

**Description**

We will discussing the introduction with respect to elasticsearch and beats after that will be covering open source HIDS agent wazuh integration with Elastic and open threat intel with virustotal.

**Speaker Bio**

I am Shrikant Gulia an elastic certified engineer and also an elastic certified analyst, currently working as senior security engineer at Reliance Jio having total 5+ yrs of experience.

**Assign to the Community team**

Africa, Europe, Middle East: @adriennedevries
Asia, Austrailia, and Pacific: @y-michael
North America and South America: @fw-at-elastic and @ullyta

**Comment by Michael-Yang-Elastic** [comment]
Hello @Shrikantgulia thanks for offering this meetup topic! Can we go ahead with email discussion? My email address is michael.yang@elastic.co.
