### ISSUE TITLE
Using Elasticsearch in a traditional infrastructure

### ISSUE THREAD

**Issue by aveleztolsa** [elastic/call-for-meetups#4]
* **Title**: Using Elasticsearch in a traditional infrastructure
* **City**: Madrid
* **Country**: Spain
* **Level**: Standard
* **Tags**: monitoring

**Description**
We are implementing Elasticsearch in a traditional infrastructure using Windows. In other talks, we saw that the people can manage their own logs as the more or less expect what is going to be received, but in with Windows we are receiving a lot of logs and it is very hard to manage them.

**Comment by immavalls** [comment]
Hi @aveleztolsa, thanks for submitting a talk! When were you thinking of doing the talk? So we can help with the organisation.

**Comment by aveleztolsa** [comment]
Hi @immavalls my idea is not to offer a talk, but could be great to organise kind of meet up where we can network with other IT techs that are using Elasticsearch for Windows event monitoring. My mates and I can share the small experience we have for people that are starting and we can receive some hints and advice from people more experienced.

When? I'm open every time

**Comment by immavalls** [comment]
Ok, so this is more of a topic you propose. Good idea, thanks @aveleztolsa! Sure there are other teams using windows and would like to share experiences. We will look into it to see what we can organize.
