### ISSUE TITLE
DevSecOps with Azure DevOps:Implementing Secure CI/CD Pipeline

### ISSUE THREAD

**Issue by rajrahul03** [elastic/call-for-meetups#43]
* **Title**: DevSecOps with Azure DevOps:Implementing Secure CI/CD Pipeline
* **Speaker**: RAHUL RAJ V V
* **City**: BENGALURU OR VIRTUAL
* **Country**: INDIA
* **Language**: ENGLISH
* **Type**: Presentation 30-45 mins 
* **Level**: Standard
* **Tags**: DevSecOps, Azure, CICD

**Description**

A demo on how to implement and integrate DevSecOps security tools into CICD pipeline. With the rise of cybersecurity threats, it's essential to integrate security practices into DevOps Practices. This is focused on the importance of integrating SAST and DAST tools in the CI/CD pipeline for identifying vulnerabilities in the source code and during runtime.

**Speaker Bio**

I am 8 Years experienced DevOps and Azure Certified Solutions Architect with specialties in architecting, building, 
and delivering highly resilient, scalable, and distributed technology platforms with a cloud-first and agile mentality. 
With a strong emphasis on customer-centricity and business-focused solution development, I have demonstrated 
expertise in solution architecture and building full IT lifecycle solutions in a diverse set of industry verticals.

**Comment by ashishtiwari1993** [comment]
Not aligned to Elastic. There was some misunderstanding with topics.
