### ISSUE TITLE
Testing Serverless integrations with Elasticsearch using LocalStack

### ISSUE THREAD

**Issue by HarshCasper** [elastic/call-for-meetups#45]
* **Title**: Testing Serverless integrations with Elasticsearch using LocalStack
* **Speaker**: Harsh Mishra (@harshcasper)
* **City**: Chennai/Delhi
* **Country**: India
* **Language**: English
* **Type**: Presentation 30-45 mins 
* **Level**: Standard
* **Tags**: serverless, testing, live-coding, workshop

**Description**

LocalStack is a fully functional local AWS cloud stack that enables cloud applications & infrastructure to be developed entirely on your local machine. LocalStack enables developers to spin up local instances of Elasticsearch and emulate the various APIs served via an ephemeral Docker container. With LocalStack, you can plug in your local Elasticsearch cluster with AWS-native serverless integrations, while developing & testing your applications, completely locally.

In this session, we will demonstrate how you can use LocalStack to develop and test serverless integrations with Elasticsearch with interactive live coding to showcase common scenarios and use cases. We will also demonstrate some advanced new features that can radically improve productivity and team collaboration patterns while building these serverless integrations for your cloud applications.

**Speaker Bio**

Hi — I am Harsh, an engineer working at LocalStack. Previously, I was a Google Summer of Code student developer at MetaCall, and a Google Season of Docs technical writer at moja global. I have worked at HackerRank, Quansight, and Red Hat, to name a few, and I am passionate about Web Engineering, Python, DevOps, and Cloud in general. I have spoken at EuroPython '21, PyCon India '21, and GitKon '22.

**Assign to the Community team**

Asia, Australia, and Pacific: @Michael-Yang-Elastic

**Comment by ashishtiwari1993** [comment]
@HarshCasper Let us know your next availability. We can check the possibility for collaboration.

**Comment by ashishtiwari1993** [comment]
This is done by Nancy :) But happy to host Harsh again.
