### ISSUE TITLE
Datastax's Astra DB integration with ElasticSearch.

### ISSUE THREAD

**Issue by pankaj-inbetween** [elastic/call-for-meetups#61]
* **Title**: Datastax's Astra DB integration with ElasticSearch.
* **Speaker**: Pankaj Gajjar, Lead Solution Architect @datastax
* **City**: [Virtual if submitting for virtual meetup] Virtual or Physical any one.
* **Country**: [Virtual if submitting for virtual meetup] India 
* **Language**: English 
* **Type**: [Presentation 30-45 mins | Lightning talk 5-10 mins] 25-30 mins 
* **Level**: [Introduction | Standard | Advanced] Standard with little advances if needs 
* **Tags**: [search, observability, security, live-coding, workshop,...] search & workshop etc 

**Description**

*A paragraph describing your proposal*
Datastax's Astra DB integration with ElasticSearch. 

**Speaker Bio**
Pankaj Gajjar 
*Short bio of the speaker*
Pankaj Gajjar, Lead Solution Architect @datastax

**Comment by ashishtiwari1993** [comment]
Thanks @pankaj-inbetween for submitting your talk. May I know for which city you would like to present ? Also if you can add more in description like 

1. what kind of integration ?
2. What we will learn from this talk ?

**Comment by ashishtiwari1993** [comment]
No revert from Pankaj. Closing this issue.
