### ISSUE TITLE
How to detect anomalies in logs, metrics, and traces to reduce MTTR with Elastic Machine Learning

### ISSUE THREAD

**Issue by ranjiniganeshan** [elastic/call-for-meetups#68]
* *How to detect anomalies in logs, metrics, and traces to reduce MTTR with Elastic Machine Learning**:
* **Ranjini G**:
* **City**: [Virtual if submitting for virtual meetup]
* **Country**: [Virtual if submitting for virtual meetup]
* **Language**: English
* **Type**: [Presentation 30-45 mins]
* **Level**: [ Standard ]
* **Tags**: [ observability]

**Description**

*A paragraph describing your proposal*

**Speaker Bio**

*Short bio of the speaker*

**Assign to the Community team**

Africa, Europe, Middle East: @adriennedevries and @naoiserush
Asia, Australia, and Pacific: @ashishtiwari1993
North America: @oliviapetrie12 and @ullyta
South America: @gabi-elastic

**Comment by ranjiniganeshan** [comment]
Description :  Discover methods for correlating telemetry data from APM agents and detecting anomalies in a specific application.

Speaker Bio
I am a Senior Software Development Engineer at Trellix and a regular contributor to Medium, where I write about FinOps best practices and other use cases. I also host and organize both online and in-person meetups.

**Comment by ashishtiwari1993** [comment]
@ranjiniganeshan Meetup URL - Meetup URL - https://www.meetup.com/elasticsearch-explorers/events/301225819/
