### ISSUE TITLE
Elasticsearch use cases at Malt

### ISSUE THREAD

**Issue by hlassiege** [elastic/call-for-meetups#7]
* **Title**: Elasticsearch use cases at Malt
* **Speaker**: Hugo Lassiège
* **City**: Lyon
* **Country**: France
* **Language**: English
* **Type**:  Presentation 30-45 mins
* **Level**: [Standard | Advanced]
* **Tags**: [rex, custom score, scoring, multi languages]

**Description**
Elasticsearch is used since 2012 at Malt. Through this presentation you'll have an overview of the way it is used on the public search engine.
We will talk about scoring through gauss decay and script functions, proximity boost, ontology, multi languages analyzers or mapping migration.

**Speaker Bio**
I am Hugo Lassiège, CTO and co-founder at Malt. I'm working in IT since 18 years, mostly as software engineer. I appreciate to discuss about architecture or organization (it's just a form or social architecture by the way), search engine, data science.
You can find me on Twitter or on my blog http://www.eventuallycoding.com
However it's in french, so, maybe not accessible for everyone :)

*Short bio of the speaker*
#java developer, CTO. Fan of distributed systems, search engine, data stuffs, even if I just scratched the surface of all those subjects.

**Comment by dadoonet** [comment]
Adding here the video of this talk that has been recorded on January 22nd, 2019 during the [ElasticFR Meetup in Paris at Malt](https://www.meetup.com/fr-FR/ElasticFR/events/253542362/). 

https://www.elastic.co/fr/videos/the-different-use-cases-of-elasticsearch-at-malt

**Comment by immavalls** [comment]
Is this the talk we'll do in Barcelona April 25th, @hlassiege ?

**Comment by hlassiege** [comment]
yes @immavalls
