### ISSUE TITLE
Tackling E-commerce Search Challenges with Elasticsearch's Powerful Features

### ISSUE THREAD

**Issue by Gurjap** [elastic/call-for-meetups#72]
* **Tackling E-commerce Search Challenges with Elasticsearch's Powerful Features**
* **Gurjap Singh**
* **Pune**
* **India**
* **English**
* **Lightning talk 5-10 mins**
* **Standard**
* **search , post_filter, aggregations, function_score**

**Description**

*This talk is about how Elasticsearch provides a flexible in-house alternative to costly SaaS options, offering powerful features—like fuzziness, analyzers, simple query search, and aggregations—that enable customized and efficient search experiences designed for e-commerce.*

**Speaker Bio**

*My name is Gurjap Singh, and I co-founded Volobot Advanced Systems in 2018. With 7 years of experience in software development, I’ve delivered solutions like ERP, mobile apps, CMS, and e-commerce platforms. I currently work as a Senior Architect (contract-based) in an e-commerce company and look forward to further exploring the tech community.*

**Comment by ashishtiwari1993** [comment]
Done with the event
