### ISSUE TITLE
De(fault) Elastic Setup ?!

### ISSUE THREAD

**Issue by sathishk** [elastic/call-for-meetups#8]
* **Title**: De(fault) Elastic Setup ?!
* **Speaker**: Sathish Kumar Thiyagarajan
* **City**: Chennai
* **Country**: India
* **Language**: English
* **Type**: [Presentation 30-45 mins]
* **Level**: [Standard]
* **Tags**: [devops]

**Description**
*Elastic is good to manage itself with ideal default configurations. But in production, it gives you options to customize the Cluster/Indexes as per your requirements which are usually overlooked by developers. It is unfortunate that many (at least most of the cased that I got associated with :) ) still uses the default settings in production. My talk is about how do we perform capacity planning to get the ideal cluster and index configurations so that we reduce the cost, increase stability and get better Index and Search performance.*

**Speaker Bio**
*I am Sathish Kumar Thiyagarajan working as a Solution Architect. I practice Open Source technologies (both by using as well as contributing) around Java, NoSQL Databases and Web. I believe speaking about/listening to technology is the best way to learn and you can find me doing the same in meetups around Chennai and Bengaluru.*

**Comment by aravindputrevu** [comment]
@xeraa Thank you. 

@sathishk Thanks for dropping the CFP. We're fortunately doing a meetup the coming week in Chennai on April 27th. Would you be interested in presenting the same? 

https://www.meetup.com/Chennai-Elastic-Fantastics/events/260664701/

**Comment by sathishk** [comment]
Sure @aravindputrevu .

**Comment by sathishk** [comment]
Hi @aravindputrevu, As discussed I will prepare the presentation for the talk.

**Comment by aravindputrevu** [comment]
Hi Sathish, 

Please keep me posted and let me know if you need any help.

**Comment by sathishk** [comment]
Hi @aravindputrevu, It was a wonderful experience to speak in our Chennai meetup. Thanks for the opportunity.

**Comment by aravindputrevu** [comment]
Thanks Sathish for talking at our meetup in Chennai yesterday. Please share your experience and what we could improve in future. Looking forward to see you again.
